x-shared-env: &shared-env
  TZ: ${TZ:-Asia/Shanghai}
x-api-env: &api-env
  TZ: ${TZ:-Asia/Shanghai}
services:
  db:
    image: postgres
    environment:
      <<: *shared-env
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - ${POSTGRES_DATA_DIR}:/data/postgres
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0 -::*
    ports:
      - "${REDIS_EXPOSE_PORT}:6379"
    networks:
      - default
  gateway:
    image: caddy
    restart: unless-stopped
    environment:
      <<: *shared-env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
      - ./gateway/.certificates:/data/caddy/certificates
    networks:
      - default
  python-api:
    image: python-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      <<: *api-env
    depends_on:
      - db
    networks:
      - default
    volumes:
      - ./api/logs:/app/logs
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - default
networks:
  default:
    driver: bridge